[package]
name = "libgen-search"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_with = "2.0"
tantivy = "0.18"
cang-jie = "0.14"
jieba-rs = { version = "0.6", features = ["default-dict"] }
csv = "1.1"
